/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.siacfinapp.frontend.ui.action.movgest;

public enum MotiviCancellazioneAccROR {
	

    
	TRIBUTI_PROPRI_IMPOSTE_TASSE_1("1.01", "1A.1","TRIBUTI PROPRI IMPOSTE/TASSE 1"),
	TRIBUTI_PROPRI_IMPOSTE_TASSE_2("1.01", "1A.2","TRIBUTI PROPRI IMPOSTE/TASSE 2"),
	TRIBUTI_PROPRI_IMPOSTE_TASSE_3("1.01", "1A.3","TRIBUTI PROPRI IMPOSTE/TASSE 3"),
	
	TRIBUTI_PROPRI_IMPOSTE_TASSE_4("1.02", "1A.1","TRIBUTI PROPRI IMPOSTE/TASSE 1"),
	TRIBUTI_PROPRI_IMPOSTE_TASSE_5("1.02", "1A.2","TRIBUTI PROPRI IMPOSTE/TASSE 2"),
	TRIBUTI_PROPRI_IMPOSTE_TASSE_6("1.02", "1A.3","TRIBUTI PROPRI IMPOSTE/TASSE 3"),
	
	QUOTA_TRIBUTI_ERARIALI_REGIONI_STATUTO_ORDINARIO_1("1.03", "1B.1","QUOTADITRIBUTIERARIALISPETTANTI ALLE REGIONI A STATUTO ORDINARIO 1"),
	QUOTA_TRIBUTI_ERARIALI_REGIONI_STATUTO_ORDINARIO_2("1.03", "1B.2","QUOTADITRIBUTIERARIALISPETTANTI ALLE REGIONI A STATUTO ORDINARIO 2"),
	QUOTA_TRIBUTI_ERARIALI_REGIONI_STATUTO_ORDINARIO_3("1.03", "1B.3","QUOTADITRIBUTIERARIALI SPETTANTI ALLE REGIONI A STATUTO ORDINARIO 3"),
	
	
	
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_1("2.01", "2.1","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 1"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_2("2.02", "2.1","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 1"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_3("2.03", "2.1","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 1"),

	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_4("2.01", "2.2","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 2"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_5("2.02", "2.2","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 2"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_6("2.03", "2.2","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 2"),
	
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_7("2.01", "2.3","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 3"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_8("2.02", "2.3","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 3"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_9("2.03", "2.3","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI 3"),

	
	
	
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_1("2.01", "2A.1","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 1"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_2("2.02", "2A.1","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 1"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_3("2.03", "2A.1","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 1"),
	
	
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_4("2.01", "2A.2","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 2"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_5("2.02", "2A.2","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 2"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_6("2.03", "2A.2","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 2"),
	
	
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_7("2.01", "2A.3","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 3"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_8("2.02", "2A.3","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 3"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_9("2.03", "2A.3","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE 3"),
	
	
	

	REDDITI_DA_CAPITALE_1("3.01", "3A.1","REDDITI DA CAPITALE"),
	REDDITI_DA_CAPITALE_2("3.01", "3A.2","REDDITI DA CAPITALE"),
	REDDITI_DA_CAPITALE_3("3.01", "3A.3","REDDITI DA CAPITALE"),
	
	ALTRE_ENTRATE_CORRENTI_1("3.02", "3B.1","ALTRE ENTRATE CORRENTI"),
	ALTRE_ENTRATE_CORRENTI_2("3.02", "3B.2","ALTRE ENTRATE CORRENTI"),
	ALTRE_ENTRATE_CORRENTI_3("3.02", "3B.3","ALTRE ENTRATE CORRENTI"),
	
	ENTRATE_EXTRATRIBUTARIE_1("3.03", "3C.1","ENTRATE EXTRATRIBUTARIE"),
	ENTRATE_EXTRATRIBUTARIE_2("3.03", "3C.2","ENTRATE EXTRATRIBUTARIE"),
	ENTRATE_EXTRATRIBUTARIE_3("3.03", "3C.3","ENTRATE EXTRATRIBUTARIE"),
	
	
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_1("4.02", "4A.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 1"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_2("4.03", "4A.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 1"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_3("4.04", "4A.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 1"),


	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_4("4.02", "4A.2","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 2"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_5("4.03", "4A.2","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 2"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_6("4.04", "4A.2","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 2"),
	
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_7("4.02", "4A.3","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 3"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_8("4.03", "4A.3","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 3"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_9("4.04", "4A.3","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE 3"),

	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_1("4.02", "4A.1.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 1"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_2("4.03", "4A.1.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 1"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_3("4.04", "4A.1.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 1"),
	
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_4("4.02", "4A.2.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 2"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_5("4.03", "4A.2.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 2"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_6("4.04", "4A.2.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 2"),

	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_7("4.02", "4A.3.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 3"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_8("4.03", "4A.3.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 3"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_9("4.04", "4A.3.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE 3"),
	
	
	
	ALIENAZIONE_BENI_1("4.01", "4B.1","ALIENAZIONE DI BENI"),
	ALIENAZIONE_BENI_2("4.01", "4B.2","ALIENAZIONE DI BENI"),
	ALIENAZIONE_BENI_3("4.01", "4B.3","ALIENAZIONE DI BENI"),
	
	ENTRATE_RISCOSSIONI_CREDITI_1("4.05", "4C.1","ENTRATE PER RISCOSSIONI DI CREDITI"),
	ENTRATE_RISCOSSIONI_CREDITI_2("4.05", "4C.2","ENTRATE PER RISCOSSIONI DI CREDITI"),
	ENTRATE_RISCOSSIONI_CREDITI_3("4.05", "4C.3","ENTRATE PER RISCOSSIONI DI CREDITI");
	
	private final String pdc;
	private final String key;
    private final String sintesi;


    MotiviCancellazioneAccROR(String pdc, String key, String sintesi) {
    	this.pdc=pdc;
        this.key = key;
        this.sintesi = sintesi;

    }
    
    public String getPdc() {
        return pdc;
    }
    
    public String getKey() {
        return key;
    }
    public String getSintesi() {
        return sintesi;
    }

}
