/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.siacfinapp.frontend.ui.action.movgest;

public enum MotiviCancellazioneROR {
	
	ORGANI_ISTITUZIONALI_1("1.01", "1.1","SPESE PER ORGANI ISTITUZIONALI 1"),
	ORGANI_ISTITUZIONALI_2("1.01", "1.2","SPESE PER ORGANI ISTITUZIONALI 2"),		
	
	PERSONALE_ONERI_ACCESSORI_1("1.02", "1B1", "SPESA PER IL PERSONALE ONERI ACCESSORI 1"),
	PERSONALE_ONERI_ACCESSORI_2("1.02", "1B2", "SPESA PER IL PERSONALE ONERI ACCESSORI 2"),	
	
	UTILIZZO_BENI_TERZI_1("1.04", "1C1","UTILIZZO BENI DI TERZI 1"),
	UTILIZZO_BENI_TERZI_2("1.04", "1C2","UTILIZZO BENI DI TERZI 2"),	
	
	INTERESSI_PASSIVI_1("1.07", "1D1","INTERESSI PASSIVI E ONERI FINANZ. DIVERSI 1"),
	INTERESSI_PASSIVI_2("1.07", "1D2","INTERESSI PASSIVI E ONERI FINANZ. DIVERSI 2"),	
	
	IMPOSTE_TASSE_1("1.08", "1E1","IMPOSTE E TASSE"),
	IMPOSTE_TASSE_2("1.08", "1E2","IMPOSTE E TASSE"),	
	
	ONERI_STRAORDINARI_1("1.09", "1F1","ONERI STRAORDINARI DELLA GESTIONE CORRENTE 1"),
	ONERI_STRAORDINARI_2("1.09", "1F2","ONERI STRAORDINARI DELLA GESTIONE CORRENTE 2"),	
	
	ACQUISTO_BENI_SERVIZI_1("1.03", "2.1","ACQUISTO DI BENI E SERVIZI 1"),
	ACQUISTO_BENI_SERVIZI_2("1.03", "2.2","ACQUISTO DI BENI E SERVIZI 2"),
	ACQUISTO_BENI_SERVIZI_3("2.01", "2.1","ACQUISTO DI BENI E SERVIZI 1"),
	ACQUISTO_BENI_SERVIZI_4("2.01", "2.2","ACQUISTO DI BENI E SERVIZI 2"),
	
    // SIAC-7970 GS 22.01.2021 Corretti PdC
	PRENOTAZIONI_DI_IMPEGNO("1.03", "2A","PRENOTAZIONI DI IMPEGNO PER GARE IN VIA DI ESPLETAMENTO (ART. 56 COMMA 4 d. Lgs. 118/2011 e CIRCOLARE IN/2014/28447)"),	
	PRENOTAZIONI_DI_IMPEGNO_1("2.01", "2A","PRENOTAZIONI DI IMPEGNO PER GARE IN VIA DI ESPLETAMENTO (ART. 56 COMMA 4 d. Lgs. 118/2011 e CIRCOLARE IN/2014/28447)"),
	// PRENOTAZIONI_DI_IMPEGNO_2("2.02", "2A","PRENOTAZIONI DI IMPEGNO PER GARE IN VIA DI ESPLETAMENTO (ART. 56 COMMA 4 d. Lgs. 118/2011 e CIRCOLARE IN/2014/28447)"),
	// PRENOTAZIONI_DI_IMPEGNO_3("2.03", "2A","PRENOTAZIONI DI IMPEGNO PER GARE IN VIA DI ESPLETAMENTO (ART. 56 COMMA 4 d. Lgs. 118/2011 e CIRCOLARE IN/2014/28447)"),
	
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_1("1.05", "3.1","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_2("1.05", "3.2","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 2"),
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_3("1.06", "3.1","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_4("1.06", "3.2","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 2"),
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_5("2.02", "3.1","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_6("2.02", "3.2","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 2"),
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_7("2.03", "3.1","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_SOGGETTI_8("2.03", "3.2","TRASFERIMENTI/CONTRIBUTI SOGGETTI A RENDICONTAZIONE 2"),	
	
	
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_1("1.05", "3B1","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_2("1.05", "3B2","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 2"),
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_3("1.06", "3B1","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_4("1.06", "3B2","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 2"),
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_5("2.02", "3B1","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_6("2.02", "3B2","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 2"),
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_7("2.03", "3B1","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 1"),
	TRASFERIMENTI_CONTRIBUTI_NON_SOGGETTI_8("2.03", "3B2","TRASFERIMENTI/CONTRIBUTI NON SOGGETTI A RENDICONTAZIONE 2"),
	
	RIMBORSO_QUOTA_1("3.01", "4.1","RIMBORSO QUOTA CAPITALE MUTUI E PRESTITI A CASSA DD.PP. 1"),
	RIMBORSO_QUOTA_2("3.01", "4.2","RIMBORSO QUOTA CAPITALE MUTUI E PRESTITI A CASSA DD.PP. 2"),	
	
	RIMBORSO_PRESTITI_1("3.04", "5.1","RIMBORSO PRESTITI OBBLIGAZIONARI 1"),
	RIMBORSO_PRESTITI_2("3.04", "5.2","RIMBORSO PRESTITI OBBLIGAZIONARI 2");
	
	private final String pdc;
	private final String key;
    private final String sintesi;


    MotiviCancellazioneROR(String pdc, String key, String sintesi) {
    	this.pdc=pdc;
        this.key = key;
        this.sintesi = sintesi;

    }
    
    public String getPdc() {
        return pdc;
    }
    
    public String getKey() {
        return key;
    }
    public String getSintesi() {
        return sintesi;
    }

}
