/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.siacfinapp.frontend.ui.action.movgest;

public enum MotiviMantenimentoAccROR {
	
	
	TRIBUTI_PROPRI_IMPOSTE_TASSE_1("1.01", "1A","TRIBUTI PROPRI IMPOSTE/TASSE"),
	TRIBUTI_PROPRI_IMPOSTE_TASSE_2("1.02", "1A","TRIBUTI PROPRI IMPOSTE/TASSE"),
	
	QUOTA_TRIBUTI_ERARIALI_REGIONI_STATUTO_ORDINARIO("1.03", "1B","QUOTA DI TRIBUTI ERARIALI SPETTANTI ALLE REGIONI A STATUTO ORDINARIO"),
	
	
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_1("2.01", "2","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_2("2.02", "2","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI"),
	ENTRATA_TRASFERIMENTI_CORRENTI_ORDINARI_3("2.03", "2","ENTRATA PER TRASFERIMENTI CORRENTI ORDINARI"),


	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_1("2.01", "2A","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_2("2.02", "2A","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE"),
	ENTRATA_TRASFERIMENTI_CORRENTI_RENDICONTAZIONE_3("2.03", "2A","ENTRATA PER TRASFERIMENTI CORRENTI A RENDICONTAZIONE"),
	
	
	
	
	REDDITI_DA_CAPITALE("3.01", "3A","REDDITI DA CAPITALE"),
	ALTRE_ENTRATE_CORRENTI("3.02", "3B","ALTRE ENTRATE CORRENTI"),
	ENTRATE_EXTRATRIBUTARIE("3.03", "3C","ENTRATE EXTRATRIBUTARIE"),
	
	
	
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_1("4.02", "4A","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_2("4.03", "4A","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_ORDINARIE_3("4.04", "4A","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE ORDINARIE"),



	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_1("4.02", "4A.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_2("4.03", "4A.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE"),
	ENTRATE_TRASFERIMENTI_CONTO_CAPITALE_RENDICONTAZIONE_3("4.04", "4A.1","ENTRATE PER TRASFERIMENTI IN CONTO CAPITALE A RENDICONTAZIONE"),
	
	
	
	ALIENAZIONE_BENI("4.01", "4B","ALIENAZIONE DI BENI"),
	ENTRATE_RISCOSSIONI_CREDITI("4.05", "4C","ENTRATE PER RISCOSSIONI DI CREDITI");
	
	private final String pdc;
	private final String key;
    private final String sintesi;


    MotiviMantenimentoAccROR(String pdc, String key, String sintesi) {
    	this.pdc=pdc;
        this.key = key;
        this.sintesi = sintesi;

    }
    
    public String getPdc() {
        return pdc;
    }
    
    public String getKey() {
        return key;
    }
    
    public String getSintesi() {
        return sintesi;
    }

}
